/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg2_daniel_trimarchi;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author X
 */
public class Main extends javax.swing.JFrame {

    adminUsuario au;
    adminAlbum aa;
    int actual = 0;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        au = new adminUsuario("./usuarios.cbm");
        aa = new adminAlbum("./albums.cbm");
        au.cargarArchivo();
        aa.cargarArchivo();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_album.getModel();
        for (int i = 0; i < aa.getListAlbum().size(); i++) {
            modelo.addElement(aa.getListAlbum().get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        pass_en = new javax.swing.JTextField();
        us_en = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jToggleButton8 = new javax.swing.JToggleButton();
        guardar = new javax.swing.JDialog();
        nom = new javax.swing.JTextField();
        us = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        album = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        art = new javax.swing.JTextField();
        albumn = new javax.swing.JTextField();
        cancion = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        ncancion = new javax.swing.JTextField();
        c_art = new javax.swing.JTextField();
        cb_album = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        duracion1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        usuario = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        us_tabla = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        programa = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        main_tree = new javax.swing.JTree();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Log In");

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel16.setText("Password:");

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setText("Usuario");

        jToggleButton8.setText("Entrar");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logLayout = new javax.swing.GroupLayout(log.getContentPane());
        log.getContentPane().setLayout(logLayout);
        logLayout.setHorizontalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logLayout.createSequentialGroup()
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(pass_en, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, logLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(us_en, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        logLayout.setVerticalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(us_en, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_en, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );

        guardar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        guardar.getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 55, 113, 42));
        guardar.getContentPane().add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 103, 113, 42));
        guardar.getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 113, 42));
        guardar.getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 113, 42));

        jLabel1.setText("Crear Usuario");
        guardar.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 11, 144, 38));

        jLabel3.setText("Nombre");
        guardar.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 95, 52));

        jLabel4.setText("Edad");
        guardar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 95, 52));

        jLabel5.setText("Password");
        guardar.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 95, 52));

        jLabel6.setText("Username");
        guardar.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 95, 52));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        guardar.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 313, 90, 40));

        album.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Crear Album");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        album.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 118, 38));

        jLabel7.setText("Nombre Del Album");
        album.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 89, 96, 42));

        jLabel8.setText("Artista");
        album.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, 96, 42));
        album.getContentPane().add(art, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 12, 136, 41));
        album.getContentPane().add(albumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 98, 136, 41));

        cancion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Crear Cancion");
        cancion.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 92, 50));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Album");
        cancion.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 92, 50));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Genero");
        cancion.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 40));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setText("Artista");
        cancion.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, 92, 50));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setText("Nombre");
        cancion.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 92, 50));
        cancion.getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 103, 40));
        cancion.getContentPane().add(ncancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 46, 103, 40));
        cancion.getContentPane().add(c_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 103, 40));

        cb_album.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cancion.getContentPane().add(cb_album, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, 40));

        jButton4.setText("Crear Cancion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        cancion.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 110, 40));
        cancion.getContentPane().add(duracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 103, 40));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setText("Duracion (Seg)");
        cancion.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 100, 40));

        us_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Password", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(us_tabla);

        jToggleButton2.setText("Eliminar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Modificar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuarioLayout = new javax.swing.GroupLayout(usuario.getContentPane());
        usuario.getContentPane().setLayout(usuarioLayout);
        usuarioLayout.setHorizontalGroup(
            usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(usuarioLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usuarioLayout.setVerticalGroup(
            usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTextField1.setText("jTextField1");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Spotify");
        main_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(main_tree);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel18.setText("MENU PRINCIPAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Explorar", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crear PlayList", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver PlayList", jPanel3);

        jMenu1.setText("Online");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        programa.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout programaLayout = new javax.swing.GroupLayout(programa.getContentPane());
        programa.getContentPane().setLayout(programaLayout);
        programaLayout.setHorizontalGroup(
            programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        programaLayout.setVerticalGroup(
            programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("Usuarios");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 80, 89, 67));

        jToggleButton4.setText("Albums");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 80, 89, 67));

        jToggleButton5.setText("Guardar Usuario");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 80, -1, 67));

        jToggleButton6.setText("Cargar Usuarios");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 182, 120, 62));

        jToggleButton7.setText("Log in");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 182, 89, 62));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Menu Principal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 11, 204, 42));

        jButton3.setText("Canciones");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 178, 89, 71));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = nom.getText();
        String ed = edad.getText();
        String password = pass.getText();
        String user = us.getText();
        nom.setText("");
        us.setText("");
        pass.setText("");
        edad.setText("");
        Usuario temp = new Usuario(nombre, ed, user, password);
        au.setPersona(temp);
        au.escribirArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        guardar.setModal(true);
        guardar.pack();
        guardar.setAlwaysOnTop(true);
        guardar.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        album.setModal(true);
        album.pack();
        album.setAlwaysOnTop(true);
        album.setVisible(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String artista = art.getText();
            String nombre_album = albumn.getText();
            art.setText("");
            albumn.setText("");
            Album ab = new Album(artista, nombre_album);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_album.getModel();
            modelo.addElement(ab);
            cb_album.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Creacion del Album Exitosa");
            boolean existe = false;
            for (int i = 0; i < aa.getListAlbum().size(); i++) {
                if (aa.getListAlbum().get(i).equals(ab)) {
                    System.out.println("Este Album ya Existe");
                    existe = true;
                }
            }
            if (existe == false) {
                aa.getListAlbum().add(ab);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cancion.setModal(true);
        cancion.pack();
        cancion.setAlwaysOnTop(true);
        cancion.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_album.getModel();
            if (modelo.getSelectedItem() instanceof Album) {
                Album alb = (Album) modelo.getSelectedItem();
                String artista = c_art.getText();
                String Cancion = ncancion.getText();
                int dura = Integer.parseInt(duracion1.getText());
                String gener = genero.getText();
                Cancion temps = new Cancion(Cancion, artista, alb, dura, gener);
                alb.getCancion().add(temps);
                boolean existe = false;
                for (int i = 0; i < aa.getListAlbum().size(); i++) {
                    if (aa.getListAlbum().get(i).equals(alb)) {
                        existe = true;
                        System.out.println("ENtrooo y Encontro");
                        aa.getListAlbum().get(i).getCancion().add(temps);
                    }
                }
                if (existe == false) {
                    aa.getListAlbum().add(alb);
                }
                aa.escribirArchivo();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        try {
            au.cargarArchivo();
            aa.cargarArchivo();
            JOptionPane.showMessageDialog(null, "Se Cargo Exitosmente");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        us_tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Usuario", "Password", "Edad"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        DefaultTableModel modelo = (DefaultTableModel) us_tabla.getModel();
        for (int i = 0; i < au.getListaus().size(); i++) {
            Usuario tem = au.getListaus().get(i);
            Object[] e = {tem.getNombre(), tem.getUser(), tem.getPassword(), tem.getEdad()};
            modelo.addRow(e);
        }
        usuario.setModal(true);
        usuario.pack();
        usuario.setAlwaysOnTop(true);
        usuario.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) us_tabla.getModel();
        if (us_tabla.getSelectedRow() > -1) {
            int row = us_tabla.getSelectedRow();
            String nombre = modelo.getValueAt(row, 0).toString();
            String edad = modelo.getValueAt(row, 3).toString();
            String password = modelo.getValueAt(row, 2).toString();
            String user = modelo.getValueAt(row, 1).toString();
            for (int i = 0; i < au.getListaus().size(); i++) {
                Usuario tem = au.getListaus().get(i);
                if (tem.getNombre().equals(nombre) && tem.getUser().equals(user) && tem.getPassword().equals(password)) {
                    au.getListaus().remove(i);
                }
            }
            au.escribirArchivo();
            au.cargarArchivo();
            us_tabla.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Usuario", "Password", "Edad"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            modelo = (DefaultTableModel) us_tabla.getModel();
            for (int i = 0; i < au.getListaus().size(); i++) {
                Usuario tem = au.getListaus().get(i);
                Object[] e = {tem.getNombre(), tem.getUser(), tem.getPassword(), tem.getEdad()};
                modelo.addRow(e);
            }
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) us_tabla.getModel();
        if (us_tabla.getSelectedRow() > -1) {
            String n_nom = JOptionPane.showInputDialog(usuario, "Ingrese el Nuevo Nombre");
            String pass = JOptionPane.showInputDialog(usuario, "Ingrese el Nuevo Password");
            String Uss = JOptionPane.showInputDialog(usuario, "Ingrese el Nuevo Usuario");

            int row = us_tabla.getSelectedRow();
            String nombre = modelo.getValueAt(row, 0).toString();
            String edad = modelo.getValueAt(row, 3).toString();
            String password = modelo.getValueAt(row, 2).toString();
            String user = modelo.getValueAt(row, 1).toString();
            for (int i = 0; i < au.getListaus().size(); i++) {
                Usuario tem = au.getListaus().get(i);
                if (tem.getNombre().equals(nombre) && tem.getUser().equals(user) && tem.getPassword().equals(password)) {
                    au.getListaus().get(i).setNombre(n_nom);
                    au.getListaus().get(i).setUser(Uss);
                    au.getListaus().get(i).setPassword(pass);
                }
            }
            au.escribirArchivo();
            au.cargarArchivo();
            us_tabla.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Usuario", "Password", "Edad"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            modelo = (DefaultTableModel) us_tabla.getModel();
            for (int i = 0; i < au.getListaus().size(); i++) {
                Usuario tem = au.getListaus().get(i);
                Object[] e = {tem.getNombre(), tem.getUser(), tem.getPassword(), tem.getEdad()};
                modelo.addRow(e);
            }
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        log.setModal(true);
        log.pack();
        log.setAlwaysOnTop(true);
        log.setVisible(true);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel modelo=(DefaultTreeModel)main_tree.getModel();
        DefaultMutableTreeNode root=new DefaultMutableTreeNode("Spotify");
        modelo.setRoot(root);
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modelo.getRoot();      
        au.cargarArchivo();
        aa.cargarArchivo();
        String uss = us_en.getText();
        String pas = pass_en.getText();
        int actual = 0;
        boolean encontrado = false;
        for (int i = 0; i < au.getListaus().size(); i++) {
            Usuario tem = au.getListaus().get(i);
 
            if (tem.getUser().equals(uss) && tem.getPassword().equals(pas)) {
                this.actual = actual;
                encontrado = true;

            }
            actual++;
        }
        if (encontrado == false) {
            JOptionPane.showMessageDialog(log, "Usuario o Password Incorrecto");
        } else {
            us_en.setText("");
            pass_en.setText("");
            for(int i=0;i<aa.getListAlbum().size();i++){
               Album tem=aa.getListAlbum().get(i);
                    DefaultMutableTreeNode n=new DefaultMutableTreeNode(tem);
               for(int j=0;j<tem.getCancion().size();j++){
                   DefaultMutableTreeNode p=new DefaultMutableTreeNode(tem.getCancion().get(j));
                   n.add(p);
               }
               raiz.add(n);
            }
            programa.setModal(true);
            programa.pack();
            programa.setAlwaysOnTop(true);
            programa.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        programa.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog album;
    private javax.swing.JTextField albumn;
    private javax.swing.JTextField art;
    private javax.swing.JTextField c_art;
    private javax.swing.JDialog cancion;
    private javax.swing.JComboBox<String> cb_album;
    private javax.swing.JTextField duracion1;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField genero;
    private javax.swing.JDialog guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JDialog log;
    private javax.swing.JTree main_tree;
    private javax.swing.JTextField ncancion;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField pass_en;
    private javax.swing.JDialog programa;
    private javax.swing.JTextField us;
    private javax.swing.JTextField us_en;
    private javax.swing.JTable us_tabla;
    private javax.swing.JDialog usuario;
    // End of variables declaration//GEN-END:variables

}
